flashcards/urls.py
from django.conf.urls import url

from . import views

# list routes URLs to views
urlpatterns = [
    url(r'^decks/$', views.deckList, name = 'deckList'),
    url(r'^decks/([\d]+)/', views.viewCard, name='viewCard'),
    url(r'^new/$', views.addCard, name ='addCard'),
    url(r'^edit/([\d]+)/$', views.editCard, name ='editCard'),
     url(r'^delete/([\d]+)/$', views.deleteCard, name ='deleteCard'),
]

ustudy/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^flashcards/', include('flashcards.urls', namespace = 'flashcards')),
    url(r'^$', views.home, name='home'),
]

flashcards/models.py
from django.db import models
import random

class Deck(models.Model):
	title = models.CharField(max_length=128)
	
	def __str__(self):
		return self.title
	
	def get_first_card(self):
		'''Returns first card in card_set'''
		return self.card_set.first()
		
	def get_last_card(self):
		'''Returns last card in card_set'''
		return self.card_set.last()
	
	def get_random_card(self):
		'''Returns random card from deckset'''
		random_idx = random.randint(0, self.card_set.count() - 1)
		random_obj = self.card_set.all()[random_idx]
		return random_obj

class Card(models.Model):
	deckset = models.ForeignKey(Deck, null=True, blank=True)
	front = models.CharField(max_length = 300)
	back = models.CharField(max_length = 300)

	def __str__(self):
		return "{} , {}".format(self.front, self.back)
	
	def has_next_card(self):
		'''
		Returns False is card is the last card in the deck, true otherwise
		'''
		parent_deck = self.deckset
		last_card_in_deck = parent_deck.get_last_card()
		if self == last_card_in_deck:
			return False
		return True
	
	def has_prev_card(self):
		'''
		Returns False is card is the first card in the deck, false otherwise
		'''
		parent_deck = self.deckset
		first_card_in_deck = parent_deck.get_first_card()
		if self == first_card_in_deck:
			return False
		return True
		
	def get_next_card(self):
		'''
		Returns the following card using the first object in a filtered queryset
		'''
		return self.deckset.card_set.filter(id__gt=self.id).first()
		
	def get_prev_card(self):
		'''
		Returns the prev card using the last object in a filtered queryset
		'''
		return self.deckset.card_set.filter(id__lt=self.id).last()

flashcards/forms.py
from django.forms import ModelForm
from .models import Card

class CardForm(ModelForm):
	"""
	Form to enter front and back info
	"""
	class Meta:
		model = Card
		fields = ['deckset', 'front', 'back']

flashcards/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from .models import Card, Deck
from .forms import CardForm

def deckList(request):
	"""
	Gets all Card objects and renders a list with front and back attribute information
	"""
	decks = Deck.objects.all( )
	context = {'decks': decks}
	return render(request, 'flashcards/decklist.html', context)

def viewCard(request, deck_id):
	'''
	Queries database for card_id from deck_id
	'''
	deck = get_object_or_404(Deck, id=deck_id)
	card_list = deck.card_set.all()
	card = card_list.first()
	if request.method == 'GET' and 'card' in request.GET:
		card = get_object_or_404(Card, id=int(request.GET['card']))
	return render(request, 'flashcards/viewCard.html', {'card':card, 'deck':deck})
	
def addCard(request):
	'''
	Renders a form allowing a user to create a card
	'''
	if request.method == 'POST':
		# create form instance and populate with data from request (what was submitted)
		form = CardForm(request.POST)
		# check if form is valid
		if form.is_valid( ):
			# save form's data to the database
			form.save( )
			# clear the form
			form = CardForm( )
	# if this is a GET or any other method (e.g., first request to create new card) 
	# create default form instance
	else:
		form = CardForm( )
	context = {'form': form}
	return render(request, 'flashcards/addOrEditCard.html', context)
	
def editCard(request, card_id):
	'''
	Renders a form allowing a user to edit a card
	'''
	card = get_object_or_404(Card, id=card_id)
	if request.method == 'POST':
		form = CardForm(request.POST, instance=card)
		if form.is_valid( ):
			form.save( )
			form = CardForm( )
	else:
		form = CardForm(instance=card)
	context = {'form': form, 'editing':True, 'card':card}
	return render(request, 'flashcards/addOrEditCard.html', context)

def deleteCard(request, card_id):
	card = get_object_or_404(Card, id=card_id)
	card.delete()
	return HttpResponseRedirect('/')

ustudy/views.py
from django.shortcuts import HttpResponse, render

def home(request):
    '''
    Renders the home page 
    '''
    return render(request, 'home.html', context=None)

flashcards/templates/flashcards/addOrEditCard.html
{% extends 'base.html' %}

{% block title %}New Form{% endblock %}

{% block content %}
	<div class="centered">
		<h3>New Card</h3>
		<form action="" method="post">
			{% csrf_token %}
			<table>
			{{ form.as_table}}
			</table>
			<input type="submit" value="Submit" />
		</form>
		{% if editing %}
			Do you want to delete this card?
			<a class='danger centered-btn' href='{% url "flashcards:deleteCard" card.id %}' style='margin-top: 10px'>Delete This Card</a>
		{% endif %}
	</div>
{% endblock %}

flashcards/templates/flashcards/decklist.html
{% extends 'base.html' %}

{% block content %}
    <div class='landing-banner'>
        <h1 class='text-centered'>Flashcards</h1>
        <hr>
        <h4 class='text-centered'>Choose a set of flashcards from below!</h4>
    </div>
    
    {% if decks %}
        {% for deck in decks %}
            <a class='centered-btn' href='{% url "flashcards:viewCard" deck.id %}'>{{ deck }}</a><br>
        {% endfor %}
    {% else %}
        <p class='text-centered'>Oh No! There are no flashcard decks available right now, try again later!</p>
    {% endif %}
{% endblock %}

flashcards/templates/flashcards/viewCard.html
{% extends 'base.html' %}

{% block content %}
    <a class='centered-btn' href='{% url "flashcards:viewCard" deck.id %}' style='margin-top: 10px'>{{ deck }}</a>
    
    {% if card %}
        <div class='notecard'>
            <div class='notecard-nav text-centered'>
                {% if card.has_prev_card %}<a href='{% url "flashcards:viewCard" deck.id %}?card={{card.get_prev_card.id}}'>Prev</a>{% endif %}
                {% if card.has_prev_card and card.has_next_card %}<a href='{% url "flashcards:viewCard" deck.id %}?card={{deck.get_random_card.id}}'>Random</a>{% endif %}
                {% if card.has_next_card %}<a href='{% url "flashcards:viewCard" deck.id %}?card={{card.get_next_card.id}}'>Next</a>{% endif %}
            </div>
            <div class="notecard-front">
                <p class='text-centered'>Front</p>
                <div class='notecard-data'>
                    <p class='text-centered'>{{card.front}}</p>
                </div>
            </div>
            <div class="notecard-back">
                <p class='text-centered'>Back</p>
                <div class='notecard-data'>
                    <p class='text-centered'>{{card.back}}</p>
                </div>
            </div>
        </div>
         <a class='danger centered-btn' href='{% url "flashcards:editCard" card.id %}' style='margin-top: 10px'>Edit This Card</a>
         <script type='text/javascript'>
        var front = document.querySelector('.notecard-front');
        var back = document.querySelector('.notecard-back');
        var card = document.querySelector('.notecard');
        back.style.display = 'none';
        
        front.onclick = function(){
            flipCard();
        }
        
        back.onclick = function(){
            flipCard();
        }
        
        function flipCard(){
            if (front.style.display === 'none'){
                front.style.display = 'block';
            } else {
                front.style.display = 'none';
            }
            
            if (back.style.display === 'none'){
                back.style.display = 'block';
            } else {
                back.style.display = 'none';
            }
        }
    </script>
    {% else %}
        <div class="text-centered">No Cards Available! Have you tried to add one?</div>
    {% endif %}

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <title>uStudy</title>
        <link href="https://fonts.googleapis.com/css?family=Metamorphous" rel="stylesheet">
        <link rel='stylesheet' href="{% static 'css/style.css' %}">
        
    </head>
    
    
    <body>
        <div class='container'>
            <nav>
                <a href="{% url 'home' %}">uStudy</a> |
                <a href="{% url 'flashcards:deckList' %}">Decks</a> |
                <a href="{% url 'flashcards:addCard' %}">Add Card</a> |
                <a href="{% url 'home' %}">About</a> |
                <a href="{% url 'home' %}">Contact</a>
            </nav>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class='landing-banner'>
        <h1 class='text-centered'>uStudy</h1>
        <hr>
        <h4 class='text-centered'>Harness the Power of U!</h4>
    </div>
    
    <a class='centered-btn' href='{% url "flashcards:deckList" %}'>Get Started</a>
    
{% endblock %}